name: C CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - name: install dependencies
      run:  sudo apt -y update && sudo apt -y install gcc-aarch64-linux-gnu qemu-user qemu-user-static
    - name: make
      run: make
    - name: Run tests
      run: make run_tests_neon
    - name: Run benchmarks
      run: make emulate_benchmarks_neon
